// src/components/ProductCard/ProductCard.vue
<template>
  
  <RouterLink :to="`/producto/${tipo}/${id}`" :class="`product-card product-card--${tipo}`">
    <img
      :src="imagen || noDisponible"
      :alt="nombre"
      :class="`product-img ${isFallback ? 'product-img--fallback' : ''}`"
      @error="handleImageError"
    />
    <div class="product-info">
      <h3 class="product-name">{{ nombre }}</h3>
      <p class="product-price">
        {{ Number(precio).toLocaleString('es-ES', { minimumFractionDigits: 2 }) }} €
      </p>
    </div>
  </RouterLink>

</template>


<script setup>

  import { ref } from 'vue'
  import { RouterLink } from 'vue-router'
  import noDisponible from '../../assets/images/no-disponible.jpg'

  const props = defineProps({
    id: Number,
    imagen: String,
    nombre: String,
    precio: [Number, String],
    tipo: String
  })

  const isFallback = ref(false)

  const handleImageError = (e) => {
    e.target.onerror = null
    e.target.src = noDisponible
    isFallback.value = true
  }

</script>


<style scoped>

  .product-card {
    position: relative;
    border-radius: 8px;
    overflow: hidden;
    transition: transform 0.2s;
    background: #8153b3;
    box-shadow: 2px 2px 4px rgb(171, 249, 244), 6px 6px 8px rgb(125, 189, 235), 10px 10px 8px rgb(178, 133, 230);
    text-decoration: none;
    display: block;
  }

  .product-card:hover {
    transform: scale(1.03);
  }

  .product-img {
    width: 100%;
    aspect-ratio: 16 / 9;
    object-fit: contain;
    display: block;
    background-color: white;
  }

  .product-card--videojuegos .product-img {
    object-fit: cover;
  }

  .product-card--videojuegos .product-img--fallback {
    object-fit: contain;
  }

  .product-info {
    padding: 12px 16px;
    background: linear-gradient(to bottom, #7439b3, #65319c);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .product-name {
    margin: 0;
    font-size: 16px;
    font-weight: 500;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 1;
  }

  .product-price {
    margin: 0;
    font-size: 22px;
    font-weight: bold;
    color: #ffffff;
    margin-left: 16px;
    white-space: nowrap;
  }
  
</style>

// src/components/ProductCard/ProductCard.jsx
import { Link } from "react-router-dom";
import { useState } from "react";
import noDisponible from "../../assets/images/no-disponible.jpg";
import "./ProductCard.css";

function ProductCard({ id, imagen, nombre, precio, tipo }) {
  const [isFallback, setIsFallback] = useState(false);

  return (
    <Link to={`/producto/${tipo}/${id}`} className={`product-card product-card--${tipo}`}>
      <img
        src={imagen || noDisponible}
        alt={nombre}
        className={`product-img ${isFallback ? 'product-img--fallback' : ''}`}
        onError={(e) => { 
          e.target.onerror = null;
          e.target.src = noDisponible;
          setIsFallback(true);
        }}
      />
      <div className="product-info">
        <h3 className="product-name">{nombre}</h3>
        <p className="product-price">
          {Number(precio).toLocaleString('es-ES', { minimumFractionDigits: 2 })} €
        </p>
      </div>
    </Link>
  );
}

export default ProductCard;
