// src/pages/Orders/Orders.jsx
import useUserStore from '../../stores/userStore';
import { useOrders } from '../../api/useOrders';
import Header from '../../components/Header/Header';
import Footer from '../../components/Footer/Footer';
import Loading from '../../components/Loading/Loading';
import './Orders.css';

function Orders() {
  const { id } = useUserStore();
  const { orders, loading } = useOrders(id);

  return (
    <>
      <div className="background-orders">
        <Header />

        <div className="pedidos-page-wrapper">
          <div className="pedidos-page-container">
            <h2 className="pedidos-titulo">Mis pedidos</h2>
            
            {loading ? (
              <Loading />
            ) : orders.length === 0 ? (
              <p className="pedidos-vacio">No tienes pedidos todavía</p>
            ) : (
              <div className="pedidos-lista">
                {orders.map((pedido, index) => (
                <div key={pedido.id} className="pedido-card">
                  <div className="pedido-header">
                    <span className="pedido-id">Pedido #{orders.length - index}</span>
                    <span className="pedido-fecha">
                      {new Date(pedido.fecha).toLocaleDateString('es-ES', {
                        day: 'numeric',
                        month: 'long',
                        year: 'numeric'
                      })}
                    </span>
                    <span className={`pedido-estado pedido-estado--${pedido.estado}`}>
                      {pedido.estado}
                    </span>
                  </div>
                  
                  <div className="pedido-productos">
                    {pedido.productos?.map((producto, i) => (
                      <div key={i} className="pedido-producto">
                        <div className="pedido-producto-info">
                          <span className="pedido-producto-nombre">
                            {producto.nombre}
                            {producto.plataforma && (
                              <span className="pedido-producto-plataforma"> ({producto.plataforma})</span>
                            )}
                          </span>
                          <span className="pedido-producto-cantidad">Cantidad: {producto.cantidad}</span>
                        </div>
                        <span className="pedido-producto-precio">{producto.precio} €</span>
                      </div>
                    ))}
                  </div>

                {pedido.envio && (
                  <div className="pedido-envio">
                    <h4 className="pedido-envio-titulo">Información de envío</h4>
                    <p className="pedido-envio-datos">
                      {pedido.envio.calle}, {pedido.envio.numeroCasa}<br />
                      {pedido.envio.codigoPostal} {pedido.envio.ciudad}<br />
                      {pedido.envio.region === 'canarias' ? 'Islas Canarias' : 'Península y Baleares'}
                      {pedido.envio.telefono && ` • Tel: +34 ${pedido.envio.telefono}`}
                    </p>
                  </div>
                )}
                  
                  <div className="pedido-footer">
                    <span className="pedido-total-label">Total:</span>
                    <span className="pedido-total-valor">{pedido.total} €</span>
                  </div>
                </div>
              ))}
            </div>
          )}
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}

export default Orders;

// src/pages/Orders/Orders.vue
<template>

  <div class="page-wrapper">
    <div class="background-orders">
      <Header />

      <div class="pedidos-page-wrapper">
        <div class="pedidos-page-container">
          <h2 class="pedidos-titulo">Mis pedidos</h2>

          <Loading v-if="loading" />

          <p v-else-if="orders.length === 0" class="pedidos-vacio">
            No tienes pedidos todavía
          </p>

          <div v-else class="pedidos-lista">
            <div v-for="(pedido, index) in orders" :key="pedido.id" class="pedido-card">
              <div class="pedido-header">
                <span class="pedido-id">Pedido #{{ orders.length - index }}</span>
                <span class="pedido-fecha">
                  {{ new Date(pedido.fecha).toLocaleDateString('es-ES', {
                    day: 'numeric', month: 'long', year: 'numeric'
                  }) }}
                </span>
                <span :class="`pedido-estado pedido-estado--${pedido.estado}`">{{ pedido.estado }}</span>
              </div>

              <div class="pedido-productos">
                <div v-for="(producto, i) in pedido.productos" :key="i" class="pedido-producto">
                  <div class="pedido-producto-info">
                    <span class="pedido-producto-nombre">
                      {{ producto.nombre }}
                      <span v-if="producto.plataforma" class="pedido-producto-plataforma"> ({{ producto.plataforma
                        }})</span>
                    </span>
                    <span class="pedido-producto-cantidad">Cantidad: {{ producto.cantidad }}</span>
                  </div>
                  <span class="pedido-producto-precio">{{ producto.precio }} €</span>
                </div>
              </div>

              <div v-if="pedido.envio" class="pedido-envio">
                <h4 class="pedido-envio-titulo">Información de envío</h4>
                <p class="pedido-envio-datos">
                  {{ pedido.envio.calle }}, {{ pedido.envio.numeroCasa }}<br />
                  {{ pedido.envio.codigoPostal }} {{ pedido.envio.ciudad }}<br />
                  {{ pedido.envio.region === 'canarias' ? 'Islas Canarias' : 'Península y Baleares' }}
                  {{ pedido.envio.telefono ? ` • Tel: +34 ${pedido.envio.telefono}` : '' }}
                </p>
              </div>

              <div class="pedido-footer">
                <span class="pedido-total-label">Total:</span>
                <span class="pedido-total-valor">{{ pedido.total }} €</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>

</template>

<script setup>

  import { computed } from 'vue'
  import { useUserStore } from '../../stores/userStore'
  import { useOrders } from '../../api/useOrders'
  import Header from '../../components/Header/Header.vue'
  import Footer from '../../components/Footer/Footer.vue'
  import Loading from '../../components/Loading/Loading.vue'

  const userStore = useUserStore()
  const userId = computed(() => userStore.id)
  const { orders, loading } = useOrders(userId)

  </script>


  <style scoped>

  .background-orders {
    background-image: url('../../assets/images/backgroundProfile.jpg');
    background-size: cover;
    background-position: center 0%;
    min-height: 100vh;
    padding-bottom: 40px;
  }

  .pedidos-page-wrapper {
    min-height: calc(100vh - 200px);
    max-width: 1000px;
    margin: 40px auto 0;
    padding: 0 20px;
  }

  .pedidos-page-container {
    min-height: 500px;
    background: #9c70ccaf;
    border-radius: 12px;
    padding: 30px;
    box-shadow: 0 6px 18px rgba(60, 60, 226, 0.4);
    width: 100%;
    box-sizing: border-box;
  }

  .pedidos-titulo {
    color: #ffffff;
    margin: 0 0 30px 0;
    padding-bottom: 20px;
    font-weight: 700;
    border-bottom: 2px solid rgba(255, 255, 255, 0.2);
  }

  .pedidos-vacio {
    color: rgba(255, 255, 255, 0.9);
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 300px;
  }

.pedidos-lista {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

  .pedido-card {
    background: rgba(255, 255, 255, 0.1);
    border-radius: 12px;
    padding: 28px;
    border: 1px solid rgba(255, 255, 255, 0.15);
    display: flex;
    flex-direction: column;
    gap: 20px;
    transition: transform 0.2s ease, box-shadow 0.2s ease;
  }

  .pedido-card:hover {
    transform: translateY(-2px);
    background: rgba(255, 255, 255, 0.15);
  }

  .pedido-header {
    display: flex;
    align-items: center;
    gap: 20px;
    flex-wrap: wrap;
    padding-bottom: 16px;
    border-bottom: 2px solid rgba(255, 255, 255, 0.2);
  }

.pedido-id { color: #ffffff; font-weight: 700; font-size: 18px; }
.pedido-fecha { color: rgba(255, 255, 255, 0.8); font-size: 15px; margin-left: auto; }

.pedido-fecha {
  color: rgba(255, 255, 255, 0.8);
  font-size: 15px;
  margin-left: auto;
}

.pedido-estado {
  padding: 6px 16px;
  border-radius: 20px;
  font-size: 13px;
  font-weight: 600;
  text-transform: capitalize;
}

.pedido-estado--procesando {
  background: rgba(241, 15, 207, 0.35);
  color: #ffffff;
  border: 1px solid #f10fde;
}

.pedido-estado--pendiente {
  background: rgba(241, 196, 15, 0.35);
  color: #ffffff;
  border: 1px solid #f1c40f;
}

.pedido-estado--enviado {
  background: rgba(52, 152, 219, 0.35);
  color: #ffffff;
  border: 1px solid #3498db;
}

.pedido-estado--entregado {
  background: rgba(46, 204, 113, 0.35);
  color: #ffffff;
  border: 1px solid #2ecc71;
}

.pedido-estado--cancelado {
  background: rgba(231, 76, 60, 0.35);
  color: #ffffff;
  border: 1px solid #e74c3c;
}

.pedido-productos {
  display: flex;
  flex-direction:
    column;
  gap: 12px;
}

.pedido-producto {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 12px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 8px;
}

.pedido-producto-info {
  display: flex;
  flex-direction: column;
  gap: 4px;
  flex: 1;
}

.pedido-producto-nombre {
  color: #ffffff;
  font-size: 15px;
  font-weight: 600;
}

.pedido-producto-plataforma {
  color: rgba(255, 255, 255, 0.75);
  font-weight: 500;
}

.pedido-producto-cantidad {
  color: rgba(255, 255, 255, 0.7);
  font-size: 13px;
}

.pedido-producto-precio {
  color: #ffffff;
  font-size: 16px;
  font-weight: 700;
  white-space: nowrap;
}

.pedido-envio {
  padding: 16px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 8px;
  border-left: 4px solid rgba(255, 255, 255, 0.3);
}

  .pedido-envio-titulo {
    color: rgba(255, 255, 255, 0.9);
    font-size: 14px;
    font-weight: 600;
    margin: 0 0 8px 0;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

.pedido-envio-datos {
  color: rgba(255, 255, 255, 0.8);
  font-size: 14px;
  line-height: 1.6;
  margin: 0;
}

  .pedido-footer {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    gap: 12px;
    padding-top: 16px;
    border-top: 2px solid rgba(255, 255, 255, 0.2);
  }

.pedido-total-label {
  color: rgba(255, 255, 255, 0.8);
  font-size: 16px;
  font-weight: 500;
}

.pedido-total-valor {
  color: #ffffff;
  font-size: 24px;
  font-weight: 700;
}

@media (max-width: 768px) {
  .pedidos-page-wrapper {
    padding: 0 16px;
  }

  .pedidos-page-container {
    padding: 20px;
  }

  .pedidos-titulo {
    font-size: 28px;
    margin-bottom: 24px;
    padding-bottom: 16px;
  }

  .pedido-card {
    padding: 20px;
  }

  .pedido-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .pedido-fecha {
    margin-left: 0;
  }

  .pedido-producto {
    flex-direction: column;
    align-items: flex-start;
  }

  .pedido-producto-precio {
    align-self: flex-end;
  }

  .pedido-footer {
    flex-direction: column;
    align-items: flex-end;
  }
}
</style>
